version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - type: bind
        source: ./config/prometheus
        target: /etc/prometheus

  grafana:
    image: grafana/grafana
    network_mode: host
    depends_on:
      - prometheus
    user: 0:0
    volumes:
      - type: bind
        source: ./config/grafana
        target: /etc/grafana
      - type: bind
        source: ./storage/grafana
        target: /var/lib/grafana
