version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    network_mode: host
    volumes:
      - type: bind
        source: ./prometheus.yml
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    network_mode: host
    depends_on:
      - prometheus
    user: 0:0
    volumes:
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ../storage/grafana
        target: /var/lib/grafana
